# Site settings
title: Site Title
description: Description
email: email@site.com


#-------------------------
# Build settings

markdown: kramdown
permalink: pretty

port: 3000

sass:
  sass_dir: assets/css
  style: :nested
