# Site settings
title: Artist Theme
email: artists@email
description: "Designer // Developer"


# Build settings

markdown: kramdown
permalink: pretty

port: 3000

sass:
  sass_dir: assets/css
  style: :nested
