# Site settings
title: Simply Thrilled
email: artists@email
description: "Record Label"


# Build settings

markdown: kramdown
permalink: pretty

port: 3000

sass:
  sass_dir: assets/css
  style: :nested
